services:
  mysql:
    image: mariadb:11.4
    logging:
      driver: none
    command: ["--max-allowed-packet=512M"]
    volumes:
      - mariadb-data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - default
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    volumes:
      - litespeed-conf:/usr/local/lsws/conf
      - litespeed-admin-conf:/usr/local/lsws/admin/conf
      - litespeed-bin:/usr/local/bin
      - litespeed-sites:/var/www/vhosts/
      - litespeed-acme:/root/.acme.sh/
      - litespeed-logs:/usr/local/lsws/logs/
    ports:
      # - 80:80
      # - 443:443
      # - 443:443/udp
      - 7080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      PMA_HOST: mysql
    restart: always
    networks:
      - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    volumes:
      # FIXED: Removed the invalid file mount and only kept the data volume
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge

# This block defines all the named volumes for Coolify to create
volumes:
  mariadb-data:
  litespeed-conf:
  litespeed-admin-conf:
  litespeed-bin:
  litespeed-sites:
  litespeed-acme:
  litespeed-logs:
  redis-data: